max_players_per_game: 2 # CANNOT EXEED 10
max_game_duration: 90
max_username_length: 12
min_number_of_players: 1
max_port_number: 65535

# Client exclusive
screen_size_x: 800
screen_size_y: 600
window_name: "JazzJackRabbit 2"
target_fps: 60

# Client exclusive debug values
debug_hostname: "localhost"
debug_port: 1002

# Server exlusive
target_ticks_per_second: 200
max_instructions_per_tick: 100

# Player Parameters
starting_points: 0
max_life: 100
starting_ammo_gun_1: 20
starting_ammo_gun_2: 0

